"""initial schema

Revision ID: 0523298d7ffa
Revises: 
Create Date: 2025-12-16 12:54:21.948936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0523298d7ffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('schema_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('slug'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_schema_name'), 'tenants', ['schema_name'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_slug'), 'tenants', ['slug'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_tenants_slug'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_schema_name'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    # ### end Alembic commands ###
